# Generated by Django 5.0.6 on 2024-06-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trinity", "0002_alter_activities_date_time_alter_activities_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="planned",
            field=models.BooleanField(default=False),
        ),
    ]
