# Generated by Django 5.0.6 on 2024-07-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0003_activities_planned'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
