# Generated by Django 5.0.6 on 2024-07-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0004_activities_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='comments',
            new_name='comment',
        ),
    ]
